
<p> Fonte de dados: https://www.kaggle.com/code/alyssonbispopereira/recomenda-o-de-filmes-ptbr/data

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Importando os pacotes a serem utilizados
import pandas as pd
import numpy as np

In [3]:
# Importar o arquivo com os filmes e visualizar as primeiras linhas
filmes = pd.read_csv("/content/drive/MyDrive/Datasets/movies_metadata.csv")
filmes.head()

<ipython-input-3-20a7ef1d5368>:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  filmes = pd.read_csv("/content/drive/MyDrive/Datasets/movies_metadata.csv")

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
# Importando o arquivo de avaliações e avaliando as primeiras linhas
avaliacoes = pd.read_csv("/content/drive/MyDrive/Datasets/ratings.csv")
avaliacoes.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

## Pré Processamento dos Dados

In [5]:
# Filtrando somente as colunas necessários e renomeando nome das variaveis

# Seleciona somente as variaveis que iremos utilizar
filmes = filmes[["id","original_title","original_language","vote_count"]]

# Renomeia as variaveis
filmes.rename(columns = {"id":"ID_FILME","original_title":"TITULO","original_language":"LINGUAGEM","vote_count":"QT_AVALIACOES"},inplace=True)

# Exibe as primeiras linhas do arquivo tratado
filmes.head()

<ipython-input-5-cb5a8ca27278>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filmes.rename(columns = {"id":"ID_FILME","original_title":"TITULO","original_language":"LINGUAGEM","vote_count":"QT_AVALIACOES"},inplace=True)

  ID_FILME                       TITULO LINGUAGEM  QT_AVALIACOES
0      862                    Toy Story        en         5415.0
1     8844                      Jumanji        en         2413.0
2    15602             Grumpier Old Men        en           92.0
3    31357            Waiting to Exhale        en           34.0
4    11862  Father of the Bride Part II        en          173.0

In [6]:
# Filtrando somente as colunas necessários e renomeando nome das variaveis

# Seleciona somente as variaveis que iremos utilizar
avaliacoes = avaliacoes [["userId","movieId","rating"]]

# Renomeia as variaveis
avaliacoes.rename(columns={"userId":"ID_USUARIO","movieId":"ID_FILME","rating":"AVALIACAO"},inplace=True)

# Exibe as primeiras linhas do arquivo tratado
avaliacoes.head()

<ipython-input-6-c96e070ab025>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  avaliacoes.rename(columns={"userId":"ID_USUARIO","movieId":"ID_FILME","rating":"AVALIACAO"},inplace=True)

   ID_USUARIO  ID_FILME  AVALIACAO
0           1       110        1.0
1           1       147        4.5
2           1       858        5.0
3           1      1221        5.0
4           1      1246        5.0

In [7]:
# Verificando se há valores nulos
filmes.isna().sum()

ID_FILME          0
TITULO            0
LINGUAGEM        11
QT_AVALIACOES     6
dtype: int64

In [8]:
# Como são poucos os valores nulos iremos remover porque não terá impacto nenhum
filmes.dropna(inplace=True)

In [9]:
# Verificando se há valores nulos
filmes.isna().sum()

ID_FILME         0
TITULO           0
LINGUAGEM        0
QT_AVALIACOES    0
dtype: int64

In [10]:
# Verificando se há valores nulos em avaliações
avaliacoes.isna().sum()

ID_USUARIO    0
ID_FILME      0
AVALIACAO     0
dtype: int64

In [11]:
# Verificando a quantidade de avaliacoes por usuarios
avaliacoes["ID_USUARIO"].value_counts()

ID_USUARIO
45811     18276
8659       9279
270123     7638
179792     7515
228291     7410
          ...
141473        1
196897        1
111231        1
193655        1
193683        1
Name: count, Length: 270896, dtype: int64

In [12]:
# Vamos pegar o ID_USUARIO somente de usuários que fizeram mais de 999 avaliações
qt_avaliacoes = avaliacoes["ID_USUARIO"].value_counts() > 999
y = qt_avaliacoes[qt_avaliacoes].index
y.shape

(2509,)

In [13]:
# Visualizando os usuarios selecionados
y

Index([ 45811,   8659, 270123, 179792, 228291, 243443,  98415, 229879,  98787,
       172224,
       ...
       269212, 257117,  76945,  30733, 196384,  53075, 220764, 214328,  14354,
       182812],
      dtype='int64', name='ID_USUARIO', length=2509)

In [14]:
# visualizando o tamanho do dataset Avaliações
avaliacoes.shape

(26024289, 3)

In [15]:
# Pegando somente avaliacoes dos usuarios que avaliaram mais de 999 vezes
avaliacoes = avaliacoes[avaliacoes["ID_USUARIO"].isin(y)]

In [16]:
# visualizando o tamanho do dataset Avaliações
avaliacoes.shape

(3844582, 3)

In [17]:
# Visualizando os DataFrame Avaliacoes
avaliacoes.head()

       ID_USUARIO  ID_FILME  AVALIACAO
17291         229         1        3.0
17292         229         2        3.0
17293         229         4        2.0
17294         229         5        1.0
17295         229         7        2.0

In [18]:
# Visualizando o DataFrame Filmes
filmes.head()

  ID_FILME                       TITULO LINGUAGEM  QT_AVALIACOES
0      862                    Toy Story        en         5415.0
1     8844                      Jumanji        en         2413.0
2    15602             Grumpier Old Men        en           92.0
3    31357            Waiting to Exhale        en           34.0
4    11862  Father of the Bride Part II        en          173.0

In [19]:
# Vamos usar os filmes que possuem somente uma quantidade de avaliações superior a 999 avaliações
filmes = filmes[filmes["QT_AVALIACOES"]> 999]

In [20]:
# Vamos agrupar e visualizar a quantidade de filmes pela linguagem
filmes_linguagem = filmes["LINGUAGEM"].value_counts()
filmes_linguagem.head(20)

LINGUAGEM
en    1100
fr       5
ja       5
it       3
ko       2
pt       1
de       1
es       1
cn       1
sv       1
id       1
Name: count, dtype: int64

In [21]:
# Selecionar somente os filmes da linguagem EN (English)
filmes = filmes[filmes["LINGUAGEM"]=="en"]
filmes.head()

   ID_FILME     TITULO LINGUAGEM  QT_AVALIACOES
0       862  Toy Story        en         5415.0
1      8844    Jumanji        en         2413.0
5       949       Heat        en         1886.0
9       710  GoldenEye        en         1194.0
15      524     Casino        en         1343.0

In [22]:
# Visualizar os tipos de dados das variaveis
filmes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1100 entries, 0 to 44842
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID_FILME       1100 non-null   object
 1   TITULO         1100 non-null   object
 2   LINGUAGEM      1100 non-null   object
 3   QT_AVALIACOES  1100 non-null   float64
dtypes: float64(1), object(3)
memory usage: 43.0+ KB

In [23]:
avaliacoes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3844582 entries, 17291 to 26023521
Data columns (total 3 columns):
 #   Column      Dtype
---  ------      -----
 0   ID_USUARIO  int64
 1   ID_FILME    int64
 2   AVALIACAO   float64
dtypes: float64(1), int64(2)
memory usage: 117.3 MB

In [28]:
# Precisamos converter a variavel ID_FILME em inteiro
filmes["ID_FILME"] = filmes["ID_FILME"].astype(int)
avaliacoes["ID_FILME"] = avaliacoes["ID_FILME"].astype(int)

In [27]:
# Verificando a quantidade de filmes pelo tamanho do arquivo
filmes.shape

(1100, 4)

In [29]:
filmes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1100 entries, 0 to 44842
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID_FILME       1100 non-null   int64
 1   TITULO         1100 non-null   object
 2   LINGUAGEM      1100 non-null   object
 3   QT_AVALIACOES  1100 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 43.0+ KB

In [30]:
avaliacoes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3844582 entries, 17291 to 26023521
Data columns (total 3 columns):
 #   Column      Dtype
---  ------      -----
 0   ID_USUARIO  int64
 1   ID_FILME    int64
 2   AVALIACAO   float64
dtypes: float64(1), int64(2)
memory usage: 117.3 MB

In [31]:
# Concatenando os dataframes
avaliacoes_e_filmes = avaliacoes.merge(filmes, on="ID_FILME")
avaliacoes_e_filmes.head()

,ID_USUARIO,ID_FILME,AVALIACAO,TITULO,LINGUAGEM,QT_AVALIACOES
0,229,12,1.0,Finding Nemo,en,6292.0
1,229,70,3.0,Million Dollar Baby,en,2519.0
2,229,77,3.0,Memento,en,4168.0
3,229,85,3.0,Raiders of the Lost Ark,en,3949.0
4,229,106,4.0,Predator,en,2129.0

In [32]:
# Verificando a quantidade de filmes com avaliacoes pelo tamanho do arquivo
avaliacoes_e_filmes.shape

(189882, 6)

In [33]:
# Verificando se há valores nulos
avaliacoes_e_filmes.isna().sum()

ID_USUARIO       0
ID_FILME         0
AVALIACAO        0
TITULO           0
LINGUAGEM        0
QT_AVALIACOES    0
dtype: int64

In [34]:
# Vamos visualizar as primeiras 20 linhas do arquivo
avaliacoes_e_filmes.head(20)

,ID_USUARIO,ID_FILME,AVALIACAO,TITULO,LINGUAGEM,QT_AVALIACOES
0,229,12,1.0,Finding Nemo,en,6292.0
1,229,70,3.0,Million Dollar Baby,en,2519.0
2,229,77,3.0,Memento,en,4168.0
3,229,85,3.0,Raiders of the Lost Ark,en,3949.0
4,229,106,4.0,Predator,en,2129.0
5,229,141,1.0,Donnie Darko,en,3574.0
6,229,153,2.0,Lost in Translation,en,1943.0
7,229,161,3.0,Ocean's Eleven,en,3857.0
8,229,170,3.0,28 Days Later,en,1816.0
9,229,176,4.0,Saw,en,2255.0
10,229,180,2.0,Minority Report,en,2663.0
11,229,185,2.0,A Clockwork Orange,en,3432.0
12,229,196,3.0,Back to the Future Part III,en,2978.0
13,229,235,3.0,Stand by Me,en,1568.0
14,229,272,4.0,Batman Begins,en,7511.0
15,229,277,1.0,Underworld,en,2556.0
16,229,296,4.0,Terminator 3: Rise of the Machines,en,2177.0
17,229,322,4.0,Mystic River,en,1473.0
18,229,329,2.0,Jurassic Park,en,4956.0
19,229,345,4.0,Eyes Wide Shut,en,1266.0

In [35]:
# Vamos descartar os valores duplicados, para que não tenha problemas de termos o mesmo usuário avaliando o mesmo filme
# diversas vezes
avaliacoes_e_filmes.drop_duplicates(["ID_USUARIO","ID_FILME"], inplace=True)

In [36]:
# Visualizando se houve alteração na quantidade de registros
avaliacoes_e_filmes.shape

(189882, 6)

In [37]:
# Vamos excluir a variavel ID_FILME porque não iremos utiliza-la
del avaliacoes_e_filmes["ID_FILME"]

In [38]:
# DataFrame sem a variavel ID_FILME
avaliacoes_e_filmes.head(20)

,ID_USUARIO,AVALIACAO,TITULO,LINGUAGEM,QT_AVALIACOES
0,229,1.0,Finding Nemo,en,6292.0
1,229,3.0,Million Dollar Baby,en,2519.0
2,229,3.0,Memento,en,4168.0
3,229,3.0,Raiders of the Lost Ark,en,3949.0
4,229,4.0,Predator,en,2129.0
5,229,1.0,Donnie Darko,en,3574.0
6,229,2.0,Lost in Translation,en,1943.0
7,229,3.0,Ocean's Eleven,en,3857.0
8,229,3.0,28 Days Later,en,1816.0
9,229,4.0,Saw,en,2255.0
10,229,2.0,Minority Report,en,2663.0
11,229,2.0,A Clockwork Orange,en,3432.0
12,229,3.0,Back to the Future Part III,en,2978.0
13,229,3.0,Stand by Me,en,1568.0
14,229,4.0,Batman Begins,en,7511.0
15,229,1.0,Underworld,en,2556.0
16,229,4.0,Terminator 3: Rise of the Machines,en,2177.0
17,229,4.0,Mystic River,en,1473.0
18,229,2.0,Jurassic Park,en,4956.0
19,229,4.0,Eyes Wide Shut,en,1266.0

In [39]:
# Agora precisamos fazer um PIVOT. O que queremos é que cada ID_USUARIO seja uma variavel com o respectivo valor de nota
# para cada filme avaliado
filmes_pivot = avaliacoes_e_filmes.pivot_table(columns="ID_USUARIO",index = "TITULO", values="AVALIACAO")
# Avaliar o arquivo transformado para PIVOT
filmes_pivot.head(20)

ID_USUARIO,229,231,741,836,1104,1136,1243,1380,1652,1846,...,269632,269750,269913,270071,270123,270213,270237,270564,270654,270887
TITULO,,,,,,,,,,,,,,,,,,,,,
10 Things I Hate About You,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.5,NaN,3.0,3.0,NaN,NaN,NaN,NaN,NaN
12 Angry Men,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN
127 Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.5,2.0,NaN,NaN,NaN,NaN
2 Fast 2 Furious,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001: A Space Odyssey,NaN,NaN,3.5,2.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,4.0,NaN,NaN,NaN,NaN,NaN
27 Dresses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28 Days Later,3.0,NaN,2.0,3.0,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,2.5,3.0,NaN,NaN,3.0,NaN
28 Weeks Later,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,4.0,1.0,...,NaN,0.5,3.0,1.0,2.0,3.0,NaN,2.5,NaN,NaN
300,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.5,4.0,3.0,3.0,1.5,NaN
3:10 to Yuma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4: Rise of the Silver Surfer,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.5,NaN,1.0,NaN,NaN,NaN,NaN
50 First Dates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN,NaN
8 Mile,NaN,NaN,2.5,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,1.5,NaN,2.0,0.5,3.0,1.0,NaN,NaN,NaN
A Beautiful Mind,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Clockwork Orange,2.0,3.0,2.5,3.5,NaN,NaN,NaN,NaN,2.0,2.0,...,NaN,2.0,3.0,2.5,1.0,3.0,2.0,NaN,3.0,5.0
A Nightmare on Elm Street,3.0,2.5,3.0,1.5,4.0,3.0,5.0,3.0,4.0,4.0,...,4.0,3.0,3.0,3.5,3.0,4.0,3.0,2.5,3.0,5.0
A.I. Artificial Intelligence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AVP: Alien vs. Predator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ace Ventura: Pet Detective,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN

In [40]:
# Os valores que são nulos iremos preencher com ZERO
filmes_pivot.fillna(0,inplace = True)
filmes_pivot.head()

ID_USUARIO,229,231,741,836,1104,1136,1243,1380,1652,1846,...,269632,269750,269913,270071,270123,270213,270237,270564,270654,270887
TITULO,,,,,,,,,,,,,,,,,,,,,
10 Things I Hate About You,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.5,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0
12 Angry Men,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0
127 Hours,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1408,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.5,2.0,0.0,0.0,0.0,0.0
2 Fast 2 Furious,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
# Vamos importar o csr_matrix do pacote SciPy
# Esse método possibilita criarmos uma matriz sparsa
from scipy.sparse import csr_matrix

# Vamos transformar o nosso dataset em uma matriz sparsa
filmes_sparse = csr_matrix(filmes_pivot)

In [42]:
# Tipo do objeto
type(filmes_sparse)

scipy.sparse._csr.csr_matrix

In [43]:
# Vamos importar o algoritmo KNN do SciKit Learn
from sklearn.neighbors import NearestNeighbors

In [44]:
# Criando e treinando o modelo preditivo
modelo = NearestNeighbors(algorithm="brute")
modelo.fit(filmes_sparse)

NearestNeighbors(algorithm='brute')

## Vamos fazer previsões de sugestões de filmes

In [45]:
# 127 Hours
distances, sugestions = modelo.kneighbors(filmes_pivot.filter(items = ["127 Hours"], axis=0).values.reshape(1,-1))

for i in range(len(sugestions)):
  print(filmes_pivot.index[sugestions[i]])

Index(['127 Hours', 'American Hustle', 'The Expendables 2', 'Lord of War',
       'RED 2'],
      dtype='object', name='TITULO')

In [46]:
# Toy Story
distances, sugestions = modelo.kneighbors(filmes_pivot.filter(items = ["Toy Story"], axis=0).values.reshape(1,-1))

for i in range(len(sugestions)):
  print(filmes_pivot.index[sugestions[i]])

Index(['Toy Story', 'Meet the Fockers', 'Top Gun',
       'Harry Potter and the Chamber of Secrets',
       'Austin Powers: International Man of Mystery'],
      dtype='object', name='TITULO')

In [47]:
# 1408
distances, sugestions = modelo.kneighbors(filmes_pivot.filter(items = ["1408"], axis=0).values.reshape(1,-1))

for i in range(len(sugestions)):
  print(filmes_pivot.index[sugestions[i]])

Index(['1408', 'Pirates of the Caribbean: At World's End', 'Platoon', 'Snitch',
       'The Expendables 2'],
      dtype='object', name='TITULO')

In [48]:
# 2 Fast 2 Furious
distances, sugestions = modelo.kneighbors(filmes_pivot.filter(items = ["2 Fast 2 Furious"], axis=0).values.reshape(1,-1))

for i in range(len(sugestions)):
  print(filmes_pivot.index[sugestions[i]])

Index(['2 Fast 2 Furious', 'Bambi', 'The Matrix Reloaded',
       'Brokeback Mountain', 'Lord of War'],
      dtype='object', name='TITULO')

IMPLEMENTAÇÃO DE CLUSTERING

In [49]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [50]:
#Normalizando os dados para clustering
scaler = StandardScaler()
filmes_scaled = scaler.fit_transform(filmes_pivot)

In [51]:
#Aplicar KMeans
n_clusters = 8
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
filmes_pivot['Cluster'] = kmeans.fit_predict(filmes_scaled)

In [52]:
filmes_pivot.head(20)

ID_USUARIO,229,231,741,836,1104,1136,1243,1380,1652,1846,...,269750,269913,270071,270123,270213,270237,270564,270654,270887,Cluster
TITULO,,,,,,,,,,,,,,,,,,,,,
10 Things I Hate About You,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.5,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,1
12 Angry Men,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,1
127 Hours,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1408,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.5,2.0,0.0,0.0,0.0,0.0,1
2 Fast 2 Furious,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2001: A Space Odyssey,0.0,0.0,3.5,2.5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,5
27 Dresses,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
28 Days Later,3.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0,4.0,0.0,...,0.0,0.0,0.0,2.5,3.0,0.0,0.0,3.0,0.0,5
28 Weeks Later,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,...,0.5,3.0,1.0,2.0,3.0,0.0,2.5,0.0,0.0,5
300,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.5,4.0,3.0,3.0,1.5,0.0,3
3:10 to Yuma,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4: Rise of the Silver Surfer,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.5,0.0,1.0,0.0,0.0,0.0,0.0,1
50 First Dates,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0,1
8 Mile,0.0,0.0,2.5,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,1.5,0.0,2.0,0.5,3.0,1.0,0.0,0.0,0.0,1
A Beautiful Mind,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
A Clockwork Orange,2.0,3.0,2.5,3.5,0.0,0.0,0.0,0.0,2.0,2.0,...,2.0,3.0,2.5,1.0,3.0,2.0,0.0,3.0,5.0,5
A Nightmare on Elm Street,3.0,2.5,3.0,1.5,4.0,3.0,5.0,3.0,4.0,4.0,...,3.0,3.0,3.5,3.0,4.0,3.0,2.5,3.0,5.0,2
A.I. Artificial Intelligence,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
AVP: Alien vs. Predator,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
Ace Ventura: Pet Detective,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,1

In [53]:
#Função para imprimir os clusters

def imprimir_clusters(df):
    for cluster in range(n_clusters):
        print(f"\nCluster {cluster}:")
        filmes_no_cluster = df[df['Cluster'] == cluster].index.tolist()
        for filme in filmes_no_cluster:
            print(f"- {filme}")

In [54]:
#Imprimir os filmes de cada cluster
imprimir_clusters(filmes_pivot)

Cluster 0:
- The Beach
- The Last Samurai
- The Sixth Sense
- The Terminal
- X-Men Origins: Wolverine

Cluster 1:
- 10 Things I Hate About You
- 12 Angry Men
- 127 Hours
- 1408
- 2 Fast 2 Furious
- 27 Dresses
- 3:10 to Yuma
- 4: Rise of the Silver Surfer
- 50 First Dates
- 8 Mile
- A Beautiful Mind
- A.I. Artificial Intelligence
- AVP: Alien vs. Predator
- Ace Ventura: Pet Detective
- Airplane!
- Aladdin
- Aliens
- Alvin and the Chipmunks
- Amadeus
- American Gangster
- American History X
- American Hustle
- American Wedding
- Anchorman: The Legend of Ron Burgundy
- Annie Hall
- Ant-Man
- Antz
- Apocalypse Now
- Apocalypto
- Apollo 13
- Atonement
- Austin Powers: International Man of Mystery
- Avengers: Age of Ultron
- Babel
- Bambi
- Batman
- Batman & Robin
- Batman Forever
- Battle: Los Angeles
- Bee Movie
- Big
- Black Hawk Down
- Blade Runner
- Blow
- Blue Jasmine
- Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan
- Braveheart
- Bridesmaids
- Bridget Jones's Diary
- Brokeback Mountain
- Bruce Almighty
- Burn After Reading
- Captain America: The First Avenger
- Cars 2
- Casablanca
- Casper
- Catch Me If You Can
- Changeling
- Charlie and the Chocolate Factory
- Chicken Run
- Citizen Kane
- Close Encounters of the Third Kind
- Cloverfield
- Collateral
- Constantine
- Corpse Bride
- Crank
- Crash
- Dances with Wolves
- Dark Shadows
- Dead Poets Society
- Die Hard: With a Vengeance
- Divergent
- Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb
- Dracula
- Dumb and Dumber To
- E.T. the Extra-Terrestrial
- Enchanted
- Enemy at the Gates
- Equilibrium
- Escape Plan
- Eternal Sunshine of the Spotless Mind
- Evan Almighty
- Exodus: Gods and Kings
- Face/Off
- Fargo
- Fear and Loathing in Las Vegas
- Fight Club
- Finding Nemo
- First Blood
- Forrest Gump
- From Dusk Till Dawn
- Full Metal Jacket
- G.I. Joe: Retaliation
- Gangs of New York
- Gangster Squad
- Gattaca
- Ghost
- Ghostbusters
- Ghostbusters II
- Gladiator
- Godzilla
- GoldenEye
- Goldfinger
- Gone Baby Gone
- Good Will Hunting
- GoodFellas
- Grease
- Gremlins
- Groundhog Day
- Grown Ups 2
- Guardians of the Galaxy
- Hancock
- Harry Potter and the Chamber of Secrets
- Harry Potter and the Half-Blood Prince
- Harry Potter and the Order of the Phoenix
- Hellboy
- Her
- Hitch
- Home Alone
- Home Alone 2: Lost in New York
- Hook
- How the Grinch Stole Christmas
- I Am Legend
- I, Robot
- Ice Age
- Identity
- Inception
- Independence Day
- Indiana Jones and the Kingdom of the Crystal Skull
- Indiana Jones and the Temple of Doom
- Inside Man
- Inside Out
- Insidious: Chapter 2
- Insomnia
- Interstellar
- Into the Wild
- It's a Wonderful Life
- Jackie Brown
- Jumanji
- Juno
- Jurassic Park III
- Kill Bill: Vol. 2
- King Kong
- Kingdom of Heaven
- Knocked Up
- Lara Croft Tomb Raider: The Cradle of Life
- Lara Croft: Tomb Raider
- Lawless
- Lethal Weapon
- Liar Liar
- Life of Brian
- Little Miss Sunshine
- Live Free or Die Hard
- Lock, Stock and Two Smoking Barrels
- Lord of War
- Madagascar 3: Europe's Most Wanted
- Mama
- Mars Attacks!
- Mary Poppins
- Match Point
- Meet Joe Black
- Meet the Fockers
- Memento
- Men in Black
- Mirror Mirror
- Mission: Impossible III
- Moonrise Kingdom
- Moulin Rouge!
- Mr. & Mrs. Smith
- Mr. Nobody
- Mud
- Mulholland Drive
- National Treasure
- National Treasure: Book of Secrets
- Night at the Museum
- No Country for Old Men
- North by Northwest
- O Brother, Where Art Thou?
- Ocean's Thirteen
- Once Upon a Time in America
- One Flew Over the Cuckoo's Nest
- P.S. I Love You
- Pain & Gain
- Panic Room
- Pearl Harbor
- Percy Jackson & the Olympians: The Lightning Thief
- Perfume: The Story of a Murderer
- Phone Booth
- Pirates of the Caribbean: At World's End
- Pirates of the Caribbean: On Stranger Tides
- Pitch Black
- Planet Terror
- Planet of the Apes
- Platoon
- Predator
- Pretty Woman
- Pride & Prejudice
- Pulp Fiction
- R.I.P.D.
- RED 2
- Raiders of the Lost Ark
- Ratatouille
- Rear Window
- Requiem for a Dream
- Resident Evil: Apocalypse
- Resident Evil: The Final Chapter
- Road to Perdition
- RoboCop
- Rocky
- Rush Hour 2
- Salt
- Saving Private Ryan
- Saw III
- Scary Movie 2
- Schindler's List
- Se7en
- Shaun of the Dead
- Shooter
- Shrek
- Shrek 2
- Shrek the Third
- Signs
- Sin City
- Sin City: A Dame to Kill For
- Sleepy Hollow
- Snatch
- Snitch
- Snow White and the Huntsman
- Snow White and the Seven Dwarfs
- Spider-Man 2
- Spider-Man 3
- Star Wars: Episode I - The Phantom Menace
- Stardust
- Starship Troopers
- Superbad
- Superman
- Taken
- Taxi Driver
- Teenage Mutant Ninja Turtles
- The Amazing Spider-Man
- The Angry Birds Movie
- The Big Lebowski
- The Blair Witch Project
- The Blues Brothers
- The Bourne Ultimatum
- The Bucket List
- The Call
- The Chronicles of Narnia: The Lion, the Witch and the Wardrobe
- The Chronicles of Riddick
- The Curious Case of Benjamin Button
- The Da Vinci Code
- The Dark Knight
- The Empire Strikes Back
- The Expendables 2
- The Fugitive
- The Game
- The Godfather
- The Godfather: Part II
- The Godfather: Part III
- The Hitchhiker's Guide to the Galaxy
- The Holiday
- The Hunger Games: Catching Fire
- The Hunger Games: Mockingjay - Part 2
- The Incredible Hulk
- The League of Extraordinary Gentlemen
- The Lion King
- The Lord of the Rings: The Fellowship of the Ring
- The Lord of the Rings: The Return of the King
- The Lord of the Rings: The Two Towers
- The Lost World: Jurassic Park
- The Lovely Bones
- The Mask
- The Matrix
- The Matrix Reloaded
- The Matrix Revolutions
- The Mortal Instruments: City of Bones
- The Mummy
- The Mummy Returns
- The Mummy: Tomb of the Dragon Emperor
- The Number 23
- The Others
- The Patriot
- The Polar Express
- The Princess Bride
- The Purge
- The Ring
- The Shawshank Redemption
- The Shining
- The Silence of the Lambs
- The Simpsons Movie
- The Sorcerer's Apprentice
- The Terminator
- The Transporter
- The Tree of Life
- The Twilight Saga: Breaking Dawn - Part 1
- The Untouchables
- The Usual Suspects
- The Wizard of Oz
- The Wolf of Wall Street
- There Will Be Blood
- There's Something About Mary
- Tomorrowland
- Top Gun
- Total Recall
- Toy Story
- Training Day
- Trainspotting
- Transformers
- Tropic Thunder
- Troy
- Twelve Monkeys
- Underworld: Evolution
- Unforgiven
- V for Vendetta
- Van Helsing
- Vanilla Sky
- Vertigo
- Vicky Cristina Barcelona
- Wanted
- War of the Worlds
- Warrior
- Who Framed Roger Rabbit
- Wild Wild West
- X-Men: Days of Future Past

Cluster 2:
- A Nightmare on Elm Street
- Back to the Future Part II
- Bad Boys II
- Batman Returns
- Beetlejuice
- Big Fish
- Die Hard 2
- Lost in Translation
- Love Actually
- Million Dollar Baby
- Ocean's Eleven
- Ocean's Twelve
- Psycho
- Rain Man
- Reservoir Dogs
- Romeo + Juliet
- School of Rock
- Silent Hill
- Stand by Me
- The Bourne Supremacy
- The Golden Compass
- Titanic

Cluster 3:
- 300
- Alien
- American Beauty
- Back to the Future
- Batman Begins
- Being John Malkovich
- Breakfast at Tiffany's
- Charlie's Angels
- Con Air
- Die Hard
- Edward Scissorhands
- Eyes Wide Shut
- Finding Neverland
- Halloween
- Harry Potter and the Goblet of Fire
- Heat
- Hulk
- Ice Age: The Meltdown
- Lethal Weapon 2
- Mission: Impossible
- Mission: Impossible II
- Mystic River
- Notting Hill
- Office Space
- Pirates of the Caribbean: Dead Man's Chest
- Saw
- Saw II
- Space Jam
- Sunshine
- Terminator Salvation
- The Breakfast Club
- The Chronicles of Narnia: Prince Caspian
- The Green Mile
- The Island
- The Mist
- The Prestige
- Twilight
- Zodiac

Cluster 4:
- Cars
- Ghost Rider
- Madagascar

Cluster 5:
- 2001: A Space Odyssey
- 28 Days Later
- 28 Weeks Later
- A Clockwork Orange
- American Pie
- American Pie 2
- American Psycho
- Armageddon
- Back to the Future Part III
- Blood Diamond
- Casino
- Cube
- Death Proof
- Dirty Dancing
- Donnie Darko
- Harry Potter and the Philosopher's Stone
- Harry Potter and the Prisoner of Azkaban
- Hot Fuzz
- Indiana Jones and the Last Crusade
- Interview with the Vampire
- Iron Man
- Jurassic Park
- Kill Bill: Vol. 1
- L.A. Confidential
- Lucky Number Slevin
- Meet the Parents
- Minority Report
- Monsters, Inc.
- Monty Python and the Holy Grail
- Mrs. Doubtfire
- Pirates of the Caribbean: The Curse of the Black Pearl
- Return of the Jedi
- Rush Hour
- Scary Movie
- Scream
- Secret Window
- Star Wars
- Star Wars: Episode II - Attack of the Clones
- Star Wars: Episode III - Revenge of the Sith
- Terminator 2: Judgment Day
- The 40 Year Old Virgin
- The Aviator
- The Bourne Identity
- The Day After Tomorrow
- The Departed
- The Devil Wears Prada
- The Fifth Element
- The Machinist
- The Pianist
- The Thing
- Transformers: Revenge of the Fallen
- Underworld
- Valkyrie
- What Women Want
- xXx

Cluster 6:
- Horrible Bosses
- In Time
- The Village

Cluster 7:
- Bridge to Terabithia
- Dawn of the Dead
- Men in Black II
- Scarface
- Terminator 3: Rise of the Machines
- The Butterfly Effect

In [57]:
#Função de recomendação baseada em KMeans que também informa o cluster do filme

def recomendar_filme(filme_input,df):
    #Encontrar o cluster do filme entrada
    cluster_filme = df[df.index == filme_input]['Cluster'].values[0]

    #Filtrar os filmes do mesmo cluster
    recomendacoes = df[df['Cluster'] == cluster_filme].index.tolist()
    recomendacoes.remove(filme_input) #Remover o próprio filme da recomendação

    print(f"Filme de entrada: '{filme_input}' pertence ao Cluster {cluster_filme}")
    print(f"Recomendações para quem gostou de '{filme_input}':")

    for filme in recomendacoes:
        cluster_recomendado = df[df.index == filme]['Cluster'].values[0]
        print(f"- {filme} (Cluster {cluster_recomendado})")

In [60]:
#Testar a função de recomendação
filme_teste = 'Titanic' #Exemplo de filme
recomendar_filme(filme_teste,filmes_pivot)

Filme de entrada: 'Titanic' pertence ao Cluster 2
Recomendações para quem gostou de 'Titanic':
- A Nightmare on Elm Street (Cluster 2)
- Back to the Future Part II (Cluster 2)
- Bad Boys II (Cluster 2)
- Batman Returns (Cluster 2)
- Beetlejuice (Cluster 2)
- Big Fish (Cluster 2)
- Die Hard 2 (Cluster 2)
- Lost in Translation (Cluster 2)
- Love Actually (Cluster 2)
- Million Dollar Baby (Cluster 2)
- Ocean's Eleven (Cluster 2)
- Ocean's Twelve (Cluster 2)
- Psycho (Cluster 2)
- Rain Man (Cluster 2)
- Reservoir Dogs (Cluster 2)
- Romeo + Juliet (Cluster 2)
- School of Rock (Cluster 2)
- Silent Hill (Cluster 2)
- Stand by Me (Cluster 2)
- The Bourne Supremacy (Cluster 2)
- The Golden Compass (Cluster 2)

USANDO DISTÂNCIA EUCLIDIANA

In [61]:
#Função para calcular a distância euclidiana
def distancia_euclidiana(vetor1,vetor2):
    return np.sqrt(np.sum((vetor1 - vetor2)**2))

In [62]:
#Função de recomendação com KMeans e Distância Euclidiana

def recomendar_filmes_kmeans_euclidiana(filme_input,df,n_recomendacoes=5):
    #Encontrar o cluster do filme de entrada
    cluster_filme = df[df.index == filme_input]['Cluster'].values[0]

    #Filtrar os filmes do mesmo cluster
    filmes_no_cluster = df[df['Cluster'] == cluster_filme]

    #Remover o filme deentrada do cluster para não recomendá-lo
    filmes_no_cluster = filmes_no_cluster.drop(filme_input,axis=0)

    #Lista par armazenar as distâncias calculadas
    distancias = []

    #Vetor do filme de entrada (sem a coluna do cluster)
    vetor_filme_input = df.loc[filme_input].drop(['Cluster']).values

    #Calcular a distancia euclidiana entre o filme de entrada e os demais filmes do cluster
    for filme in filmes_no_cluster.index:
        vetor_filme = filmes_no_cluster.loc[filme].drop(['Cluster']).values
        distancia = distancia_euclidiana(vetor_filme_input,vetor_filme)
        distancias.append((filme, distancia))

    #Ordenar pela menor distancia (mais proximo)
    distancias_ordenadas = sorted(distancias, key=lambda x: x[1])

    #Exibir as recomendações
    print(f"Filme de entrada: '{filme_input}' pertence ao cluster '{cluster_filme}'")
    print(f"Recomendacoes para quem gostou de '{filme_input}':")

    for i in range(n_recomendacoes):
        filme_recomendado, dist = distancias_ordenadas[i]
        print(f" - {filme_recomendado} (Distância Euclidiana: {dist:.2f})")

In [63]:
#Testar a função de recomendação
filme_teste = 'Toy Story' #Exemplo de teste
recomendar_filmes_kmeans_euclidiana(filme_teste,filmes_pivot)

Filme de entrada: 'Toy Story' pertence ao cluster '1'
Recomendacoes para quem gostou de 'Toy Story':
 - Meet the Fockers (Distância Euclidiana: 30.09)
 - Top Gun (Distância Euclidiana: 30.21)
 - Harry Potter and the Chamber of Secrets (Distância Euclidiana: 30.22)
 - Austin Powers: International Man of Mystery (Distância Euclidiana: 30.23)
 - The Wizard of Oz (Distância Euclidiana: 30.38)

USANDO COMBINAÇÃO KMEANS + KNN

In [65]:
#Função de recomendação com KMeans e KNN dentro do cluster

def recomendar_filmes_kmeans_knn(filme_input,df,n_recomendacoes):
    #Encontrar o cluster do filme de entrada
    cluster_filme = df[df.index == filme_input]['Cluster'].values[0]

    #Filtrar os filmes do mesmo cluster
    filmes_no_cluster = df[df['Cluster'] == cluster_filme]

    #Remover o filme de entrada do cluster para não recomendá-lo
    filmes_no_cluster = filmes_no_cluster.drop(filme_input,axis=0)

    #Criar um modelo KNN para calcular a similaridade dentro do cluster
    knn = NearestNeighbors(n_neighbors=n_recomendacoes, algorithm='brute')
    knn.fit(filmes_no_cluster.drop(columns=['Cluster'])) #usar os dados sem a coluna de cluster

    #Encontrar as recomendações mais próximas dentro do cluster
    distances, sugestions = knn.kneighbors(df.loc[filme_input].drop(['Cluster']).values.reshape(1,-1))

    #Exibir as recomendações
    print(f"Filme de entrada: '{filme_input}' pertence ao cluster '{cluster_filme}'")
    print(f"Recomendacoes para quem gostou de '{filme_input}':")

    for i in range(len(sugestions[0])):
        filme_recomendado = filmes_no_cluster.index[sugestions[0][i]]
        cluster_recomendado = filmes_no_cluster.loc[filme_recomendado]['Cluster']
        print(f" - {filme_recomendado} (Cluster {cluster_recomendado})")

In [72]:
#Testar a função de recomendação
filme_teste = 'The Matrix' #Exemplo de filme
recomendar_filmes_kmeans_knn(filme_teste,filmes_pivot,5)

Filme de entrada: 'The Matrix' pertence ao cluster '1'
Recomendacoes para quem gostou de 'The Matrix':
 - Aliens (Cluster 1.0)
 - Harry Potter and the Order of the Phoenix (Cluster 1.0)
 - Men in Black (Cluster 1.0)
 - The Matrix Reloaded (Cluster 1.0)
 - Anchorman: The Legend of Ron Burgundy (Cluster 1.0)